services:
  mysql:
    image: mysql:8.0
    container_name: videoclub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: VIDEO_CLUB
      MYSQL_USER: videoclub_user
      MYSQL_PASSWORD: videoclub1234
    ports:
      - "3306:3306"
    volumes:
      - videoclub_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  videoclub_data: